"""
AdaptiveDefense -- Swarm-coordinated defensive posture updates.

Translates threat intelligence into concrete defense actions:
- Auto-segmentation of compromised network segments
- Countermeasure deployment based on observed TTPs
- WAF rule generation from attack payloads
- Priority-scored defense actions with TTL
"""

from __future__ import annotations

import hashlib
import logging
import re
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from ember_honeypot.models import TTPRecord, ThreatScore

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class ActionType(str, Enum):
    SEGMENT = "segment"               # Network isolation
    BLOCK_IP = "block_ip"             # Firewall block
    RATE_LIMIT = "rate_limit"         # Traffic throttling
    WAF_RULE = "waf_rule"             # WAF rule deployment
    HONEYTRAP = "honeytrap"           # Deploy additional honeypots
    ALERT = "alert"                   # Send alert only
    QUARANTINE = "quarantine"         # Full quarantine


class Priority(int, Enum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4
    EMERGENCY = 5


class DefenseAction(BaseModel):
    """A single defensive action generated by the adaptive defense engine."""

    id: UUID = Field(default_factory=uuid4)
    action_type: ActionType
    target: str  # IP, CIDR, segment name, rule ID, etc.
    ttl: int = Field(default=3600, ge=0)  # Time-to-live in seconds, 0 = permanent
    priority: Priority = Priority.MEDIUM
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime | None = None
    rule_payload: str | None = None  # For WAF rules: the actual rule text
    source_threat_score: float = Field(default=0.0, ge=0.0, le=1.0)
    description: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)

    def model_post_init(self, __context: Any) -> None:
        if self.expires_at is None and self.ttl > 0:
            self.expires_at = self.created_at + timedelta(seconds=self.ttl)


# ---------------------------------------------------------------------------
# AdaptiveDefense
# ---------------------------------------------------------------------------


class AdaptiveDefense:
    """Swarm-coordinated adaptive defense engine.

    Translates threat intelligence into prioritized defense actions.
    Supports auto-segmentation, countermeasure deployment, and WAF rule
    generation from observed attack payloads.
    """

    # MITRE technique → defense action mappings
    TTP_COUNTERMEASURES: dict[str, list[DefenseAction]] = {
        "T1071": [  # Application Layer Protocol
            DefenseAction(
                action_type=ActionType.WAF_RULE,
                target="http",
                priority=Priority.HIGH,
                ttl=7200,
                description="Block suspicious application-layer traffic",
            ),
        ],
        "T1041": [  # Exfiltration Over C2 Channel
            DefenseAction(
                action_type=ActionType.SEGMENT,
                target=" compromised_segment",
                priority=Priority.CRITICAL,
                ttl=3600,
                description="Isolate segment showing exfiltration behavior",
            ),
        ],
        "T1110": [  # Brute Force
            DefenseAction(
                action_type=ActionType.RATE_LIMIT,
                target="auth_endpoints",
                priority=Priority.HIGH,
                ttl=1800,
                description="Rate-limit authentication attempts",
            ),
        ],
        "T1190": [  # Exploit Public-Facing Application
            DefenseAction(
                action_type=ActionType.WAF_RULE,
                target="web_app",
                priority=Priority.CRITICAL,
                ttl=86400,
                description="Deploy emergency WAF rules for exploited application",
            ),
        ],
    }

    # Payload pattern → WAF rule templates
    WAF_PATTERNS: list[tuple[re.Pattern, str]] = [
        (
            re.compile(r"union\s+select", re.IGNORECASE),
            'SecRule REQUEST_BODY "@rx (?i)union\\s+select" \\\n    "id:1001,phase:2,deny,status:403,msg:\'SQL Injection\'"',
        ),
        (
            re.compile(r"<script[^>]*>", re.IGNORECASE),
            'SecRule REQUEST_BODY "@rx (?i)<script[^>]*>" \\\n    "id:1002,phase:2,deny,status:403,msg:\'XSS Attempt\'"',
        ),
        (
            re.compile(r"\.\.[/\\]", re.IGNORECASE),
            'SecRule REQUEST_URI "@rx (?i)\\.\\.[/\\\\]" \\\n    "id:1003,phase:1,deny,status:403,msg:\'Path Traversal\'"',
        ),
        (
            re.compile(r"\$\{jndi:(ldap|rmi|dns)", re.IGNORECASE),
            'SecRule REQUEST_BODY|REQUEST_HEADERS "@rx (?i)\\$\\{jndi:(ldap|rmi|dns)" \\\n    "id:1004,phase:2,deny,status:403,msg:\'Log4j/Log4Shell\'"',
        ),
        (
            re.compile(r"(curl|wget)\s+.*\|.*bash", re.IGNORECASE),
            'SecRule REQUEST_BODY "@rx (?i)(curl|wget)\\s+.*\\|.*bash" \\\n    "id:1005,phase:2,deny,status:403,msg:\'Remote Code Execution\'"',
        ),
        (
            re.compile(r"/etc/(passwd|shadow|hosts)", re.IGNORECASE),
            'SecRule REQUEST_URI "@rx (?i)/etc/(passwd|shadow|hosts)" \\\n    "id:1006,phase:1,deny,status:403,msg:\'Local File Inclusion\'"',
        ),
    ]

    def __init__(self, default_ttl: int = 3600) -> None:
        self.default_ttl = default_ttl
        self._action_log: list[DefenseAction] = []
        self._segmented_ips: set[str] = set()
        self._blocked_ips: set[str] = set()

    # -- Posture updates ------------------------------------------------------

    def update_posture(self, threat_score: ThreatScore) -> list[DefenseAction]:
        """Evaluate threat score and generate appropriate defense actions.

        Returns a list of prioritized DefenseAction objects.
        """
        actions: list[DefenseAction] = []

        if threat_score.overall >= 0.8:
            actions.append(
                DefenseAction(
                    action_type=ActionType.QUARANTINE,
                    target="all_traffic",
                    priority=Priority.EMERGENCY,
                    ttl=self.default_ttl * 2,
                    source_threat_score=threat_score.overall,
                    description=f"Emergency quarantine — threat score {threat_score.overall:.2f}",
                )
            )
        elif threat_score.overall >= 0.6:
            actions.append(
                DefenseAction(
                    action_type=ActionType.HONEYTRAP,
                    target="surrounding_segments",
                    priority=Priority.HIGH,
                    ttl=self.default_ttl,
                    source_threat_score=threat_score.overall,
                    description=f"Deploy honeytraps — threat score {threat_score.overall:.2f}",
                )
            )
        elif threat_score.overall >= 0.4:
            actions.append(
                DefenseAction(
                    action_type=ActionType.ALERT,
                    target="security_team",
                    priority=Priority.MEDIUM,
                    ttl=600,
                    source_threat_score=threat_score.overall,
                    description=f"Elevated threat alert — score {threat_score.overall:.2f}",
                )
            )

        # Sophistication-based actions
        if threat_score.sophistication >= 0.7:
            actions.append(
                DefenseAction(
                    action_type=ActionType.HONEYTRAP,
                    target="advanced_deception",
                    priority=Priority.HIGH,
                    ttl=self.default_ttl * 2,
                    source_threat_score=threat_score.overall,
                    description="Advanced attacker detected — deploy enhanced deception",
                )
            )

        # Persistence-based actions
        if threat_score.persistence >= 0.6:
            actions.append(
                DefenseAction(
                    action_type=ActionType.BLOCK_IP,
                    target="persistent_attacker",
                    priority=Priority.HIGH,
                    ttl=self.default_ttl * 4,
                    source_threat_score=threat_score.overall,
                    description="Persistent attacker — extended block",
                )
            )

        for action in actions:
            self._action_log.append(action)

        logger.info(
            "Adaptive posture update: score=%d, actions_generated=%d",
            threat_score.overall,
            len(actions),
        )
        return actions

    # -- Auto-segmentation ----------------------------------------------------

    def auto_segment(self, attacker_ip: str) -> bool:
        """Trigger network isolation for a specific attacker IP.

        Returns True if the segmentation was successfully triggered.
        """
        if attacker_ip in self._segmented_ips:
            logger.debug("IP %s already segmented", attacker_ip)
            return True

        self._segmented_ips.add(attacker_ip)

        action = DefenseAction(
            action_type=ActionType.SEGMENT,
            target=attacker_ip,
            priority=Priority.HIGH,
            ttl=self.default_ttl,
            description=f"Auto-segment attacker IP {attacker_ip}",
        )
        self._action_log.append(action)

        logger.info("Auto-segment triggered for %s", attacker_ip)
        return True

    def is_segmented(self, attacker_ip: str) -> bool:
        """Check if an IP is currently in a segmented network."""
        return attacker_ip in self._segmented_ips

    def lift_segmentation(self, attacker_ip: str) -> bool:
        """Remove network segmentation for an IP."""
        if attacker_ip in self._segmented_ips:
            self._segmented_ips.discard(attacker_ip)
            logger.info("Segmentation lifted for %s", attacker_ip)
            return True
        return False

    # -- Countermeasure deployment -------------------------------------------

    def deploy_countermeasures(self, ttps: list[TTPRecord]) -> list[DefenseAction]:
        """Deploy swarm-recommended countermeasures based on observed TTPs.

        Maps each TTP to pre-configured defense actions and returns
        the combined list of actions to take.
        """
        actions: list[DefenseAction] = []

        for ttp in ttps:
            template_actions = self.TTP_COUNTERMEASURES.get(ttp.technique_id, [])
            for template in template_actions:
                action = template.model_copy(update={
                    "id": uuid4(),
                    "created_at": datetime.now(timezone.utc),
                    "source_threat_score": int(ttp.confidence * 100),
                    "description": f"[{ttp.technique_id}] {ttp.technique or ttp.name}: {template.description}",
                    "metadata": {
                        "tactic": ttp.tactic,
                        "technique_id": ttp.technique_id,
                        "procedure": ttp.procedure or ttp.description,
                    },
                })
                actions.append(action)
                self._action_log.append(action)

            if not template_actions:
                # Generic alert for unknown TTPs
                actions.append(
                    DefenseAction(
                        action_type=ActionType.ALERT,
                        target=f"ttp:{ttp.technique_id}",
                        priority=Priority.MEDIUM,
                        ttl=self.default_ttl,
                        description=f"Unknown TTP observed: {ttp.technique_id} — {ttp.technique or ttp.name}",
                        metadata={"tactic": ttp.tactic, "procedure": ttp.procedure or ttp.description},
                    )
                )

        logger.info(
            "Deployed %d countermeasures for %d TTPs",
            len(actions),
            len(ttps),
        )
        return actions

    # -- WAF rule generation --------------------------------------------------

    def generate_waf_rules(self, payloads: list[str]) -> list[str]:
        """Generate WAF rules from observed attack payloads.

        Matches payloads against known attack patterns and returns
        ModSecurity-compatible rule strings.
        """
        rules: list[str] = []
        matched_payloads: set[str] = set()

        for payload in payloads:
            for pattern, rule_template in self.WAF_PATTERNS:
                if pattern.search(payload):
                    rule_id = self._rule_id_from_payload(payload)
                    rule = rule_template.replace("id:100", f"id:{rule_id}")
                    if rule not in rules:
                        rules.append(rule)
                        matched_payloads.add(payload)
                    break

        if not rules:
            # Generate a generic catch-all rule if no patterns matched
            for payload in payloads[:1]:  # Just the first one
                rule_id = self._rule_id_from_payload(payload)
                rules.append(
                    f'SecRule REQUEST_BODY "@contains {payload[:30]}" \\\n    "id:{rule_id},phase:2,deny,status:403,msg:\'Suspicious payload detected\'"'
                )

        logger.info("Generated %d WAF rules from %d payloads", len(rules), len(payloads))
        return rules

    # -- History and stats ----------------------------------------------------

    def get_action_log(self, limit: int = 100) -> list[DefenseAction]:
        """Get recent defense actions, newest first."""
        return self._action_log[-limit:][::-1] if limit < len(self._action_log) else self._action_log[::-1]

    def get_active_actions(self) -> list[DefenseAction]:
        """Get currently active (non-expired) defense actions."""
        now = datetime.now(timezone.utc)
        return [
            a for a in self._action_log
            if a.expires_at is None or a.expires_at > now
        ]

    def get_stats(self) -> dict[str, Any]:
        """Return defense engine statistics."""
        action_counts: dict[str, int] = {}
        for a in self._action_log:
            action_counts[a.action_type.value] = action_counts.get(a.action_type.value, 0) + 1

        return {
            "total_actions": len(self._action_log),
            "active_actions": len(self.get_active_actions()),
            "segmented_ips": len(self._segmented_ips),
            "blocked_ips": len(self._blocked_ips),
            "action_breakdown": action_counts,
        }

    # -- Internal -------------------------------------------------------------

    def _rule_id_from_payload(self, payload: str) -> str:
        """Generate a deterministic rule ID from a payload."""
        hash_val = hashlib.sha256(payload.encode()).hexdigest()[:6]
        return f"99{int(hash_val, 16) % 9000 + 1000}"
