"""
Service Emulator Framework — pluggable emulators for SSH, HTTP, and future protocols.

Track 2a: EmberHoneypot Core + API Layer
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import secrets
import string
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Protocol

logger = logging.getLogger(__name__)


# ── Data Models ──────────────────────────────────────────────────────────


class ProtocolType(str, Enum):
    """Supported protocol types for emulation."""

    SSH = "ssh"
    HTTP = "http"
    FTP = "ftp"
    DATABASE = "database"


@dataclass
class ConnectionContext:
    """Context for an incoming connection to an emulated service."""

    source_ip: str
    source_port: int
    destination_port: int
    connected_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    session_id: str = ""
    authenticated_user: str | None = None
    working_directory: str = "/home/user"
    environment: dict[str, str] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class EmulatedResponse:
    """Response generated by an emulated service."""

    payload: str | bytes
    response_type: str = "text"  # text | binary | json | html
    status_code: int = 200
    headers: dict[str, str] = field(default_factory=dict)
    delay_ms: int = 0  # Simulated processing delay


# ── Abstract Base ────────────────────────────────────────────────────────


class ServiceEmulator(ABC):
    """Abstract base class for service emulators.

    Each emulator implements the protocol-level behavior needed to
    convincingly simulate a real service while logging all interactions.
    """

    protocol: ProtocolType = ProtocolType.SSH
    banner: str = ""
    version_string: str = ""

    def __init__(
        self,
        banner: str | None = None,
        version_string: str | None = None,
        config: dict[str, Any] | None = None,
    ) -> None:
        self.banner = banner or self.__class__.banner
        self.version_string = version_string or self.__class__.version_string
        self.config = config or {}
        self._running = False
        self._connection_count = 0
        self._command_log: list[dict[str, Any]] = []

    # ── Lifecycle ─────────────────────────────────────────────────────────

    async def start(self) -> None:
        """Start the emulator. Override for protocol-specific startup."""
        self._running = True
        logger.info("%s emulator started (banner: %s)", self.protocol.value, self.banner)

    async def stop(self) -> None:
        """Stop the emulator gracefully."""
        self._running = False
        logger.info("%s emulator stopped", self.protocol.value)

    # ── Abstract Interface ────────────────────────────────────────────────

    @abstractmethod
    async def handle_connection(
        self,
        context: ConnectionContext,
        raw_data: str | bytes,
    ) -> EmulatedResponse:
        """Handle an incoming connection/data from an attacker.

        Args:
            context: Connection metadata (IP, port, session info).
            raw_data: The raw data sent by the attacker.

        Returns:
            EmulatedResponse to send back to the attacker.
        """
        ...

    @abstractmethod
    async def get_banner(self) -> str:
        """Return the service banner string."""
        ...

    # ── Shared Helpers ────────────────────────────────────────────────────

    def _log_command(
        self,
        context: ConnectionContext,
        command: str,
        response: str,
    ) -> None:
        """Log a command for forensic analysis."""
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source_ip": context.source_ip,
            "session_id": context.session_id,
            "protocol": self.protocol.value,
            "command": command,
            "response_preview": response[:200] if response else "",
            "authenticated_user": context.authenticated_user,
        }
        self._command_log.append(entry)
        self._connection_count += 1

    @property
    def is_running(self) -> bool:
        return self._running

    @property
    def connection_count(self) -> int:
        return self._connection_count

    def get_logs(self, limit: int = 100) -> list[dict[str, Any]]:
        """Return recent command logs."""
        return self._command_log[-limit:]


# ── SSH Emulator ─────────────────────────────────────────────────────────


class SSHEmulator(ServiceEmulator):
    """Emulates an SSH server — handshake, auth, and shell interaction.

    Accepts any credentials, provides a convincing shell environment,
    and logs every command for analysis.
    """

    protocol = ProtocolType.SSH
    banner = "SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6"
    version_string = "OpenSSH_8.9"

    # Common shell responses for popular commands
    _SHELL_RESPONSES: dict[str, str] = {
        "ls": (
            "total 48\n"
            "drwxr-xr-x 5 user user 4096 Jun 15 09:23 .\n"
            "drwxr-xr-x 3 root root 4096 Jun 10 14:11 ..\n"
            "-rw------- 1 user user  892 Jun 15 08:45 .bash_history\n"
            "-rw-r--r-- 1 user user  220 Jun 10 14:11 .bash_logout\n"
            "-rw-r--r-- 1 user user 3771 Jun 10 14:11 .bashrc\n"
            "drwxrwxr-x 3 user user 4096 Jun 12 11:02 .cache\n"
            "drwx------ 3 user user 4096 Jun 12 11:02 .config\n"
            "-rw-r--r-- 1 user user  807 Jun 10 14:11 .profile\n"
            "drwx------ 2 user user 4096 Jun 14 16:33 .ssh\n"
            "-rw-r--r-- 1 user user  12K Jun 14 22:18 notes.txt\n"
            "drwxr-xr-x 4 user user 4096 Jun 13 10:47 projects"
        ),
        "ls -la": (
            "total 48\n"
            "drwxr-xr-x 5 user user 4096 Jun 15 09:23 .\n"
            "drwxr-xr-x 3 root root 4096 Jun 10 14:11 ..\n"
            "-rw------- 1 user user  892 Jun 15 08:45 .bash_history\n"
            "-rw-r--r-- 1 user user  220 Jun 10 14:11 .bash_logout\n"
            "-rw-r--r-- 1 user user 3771 Jun 10 14:11 .bashrc\n"
            "drwxrwxr-x 3 user user 4096 Jun 12 11:02 .cache\n"
            "drwx------ 3 user user 4096 Jun 12 11:02 .config\n"
            "-rw-r--r-- 1 user user  807 Jun 10 14:11 .profile\n"
            "drwx------ 2 user user 4096 Jun 14 16:33 .ssh\n"
            "-rw-r--r-- 1 user user  12K Jun 14 22:18 notes.txt\n"
            "drwxr-xr-x 4 user user 4096 Jun 13 10:47 projects"
        ),
        "pwd": "/home/user",
        "whoami": "user",
        "id": "uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev)",
        "uname -a": "Linux dev-server-03 5.15.0-105-generic #115-Ubuntu SMP Mon Mar 4 20:55:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux",
        "uname": "Linux",
        "cat /etc/os-release": (
            'PRETTY_NAME="Ubuntu 22.04.4 LTS"\n'
            "NAME=\"Ubuntu\"\n"
            "VERSION_ID=\"22.04\"\n"
            "VERSION=\"22.04.4 LTS (Jammy Jellyfish)\"\n"
            "VERSION_CODENAME=jammy\n"
            "ID=ubuntu\n"
            "HOME_URL=\"https://www.ubuntu.com/\"\n"
            "SUPPORT_URL=\"https://help.ubuntu.com/\"\n"
        ),
        "cat /proc/version": "Linux version 5.15.0-105-generic (buildd@lcy02-amd64-031) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #115-Ubuntu SMP Mon Mar 4 20:55:20 UTC 2024",
        "cat /etc/passwd": (
            "root:x:0:0:root:/root:/bin/bash\n"
            "daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\n"
            "bin:x:2:2:bin:/bin:/usr/sbin/nologin\n"
            "sys:x:3:3:sys:/dev:/usr/sbin/nologin\n"
            "sync:x:4:65534:sync:/bin:/bin/sync\n"
            "user:x:1000:1000:Alex Chen,,,:/home/user:/bin/bash\n"
            "postgres:x:106:113:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash\n"
            "www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\n"
        ),
        "ps aux": (
            "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\n"
            "root         1  0.0  0.1 167840 12160 ?        Ss   Jun10   0:03 /sbin/init\n"
            "root       512  0.0  0.2  72340 20144 ?        Ss   Jun10   0:12 /usr/lib/systemd/systemd-journald\n"
            "root       548  0.0  0.1  24144  8320 ?        Ss   Jun10   0:02 /usr/lib/systemd/systemd-networkd\n"
            "root       723  0.0  0.3 128964 24512 ?        Ss   Jun10   0:45 /usr/bin/python3 /usr/bin/networkd-dispatcher\n"
            "root       891  0.0  0.2  18724 16224 ?        Ss   Jun10   0:00 /usr/bin/dbus-daemon\n"
            "root      1023  0.0  0.1  72300  8544 ?        Ssl  Jun10   0:01 /usr/sbin/rsyslogd\n"
            "root      1089  0.0  0.1  14840  7296 ?        Ss   Jun10   0:00 /usr/sbin/cron\n"
            "root      1123  0.0  0.1  16456  8960 ?        Ss   Jun10   0:02 /usr/sbin/sshd -D\n"
            "postgres  1345  0.0  1.2 220344 96768 ?        Ss   Jun10   0:15 /usr/lib/postgresql/14/bin/postgres\n"
            "user      2041  0.1  0.4  45120 33892 pts/0    S+   09:23   0:02 -bash\n"
            "user      2089  0.0  0.0   8084  3328 pts/0    R+   09:45   0:00 ps aux"
        ),
        "free -h": (
            "              total        used        free      shared  buff/cache   available\n"
            "Mem:          7.7Gi       2.1Gi       3.8Gi       156Mi       1.8Gi       5.1Gi\n"
            "Swap:         2.0Gi          0B       2.0Gi"
        ),
        "df -h": (
            "Filesystem                         Size  Used Avail Use% Mounted on\n"
            "/dev/mapper/ubuntu--vg-ubuntu--lv  196G   45G  142G  24% /\n"
            "/dev/sda2                          2.0G  121M  1.7G   7% /boot\n"
            "/dev/sda1                          1.1G  6.1M  1.1G   1% /boot/efi"
        ),
        "ifconfig": (
            "eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\n"
            "        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255\n"
            "        inet6 fe80::a00:27ff:fe4e:66a1  prefixlen 64  scopeid 0x20<link>\n"
            "        ether 08:00:27:4e:66:a1  txqueuelen 1000  (Ethernet)\n"
            "        RX packets 124382  bytes 89234156 (89.2 MB)\n"
            "        TX packets 87321  bytes 12345678 (12.3 MB)"
        ),
        "ip addr": (
            "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN\n"
            "    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00\n"
            "    inet 127.0.0.1/8 scope host lo\n"
            "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP\n"
            "    link/ether 08:00:27:4e:66:a1 brd ff:ff:ff:ff:ff:ff\n"
            "    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0\n"
            "    inet6 fe80::a00:27ff:fe4e:66a1/64 scope link"
        ),
        "netstat -tulpn": (
            "Active Internet connections (only servers)\n"
            "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name\n"
            "tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1123/sshd\n"
            "tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1345/postgres\n"
            "tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1456/nginx\n"
            "tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      2342/python3\n"
            "tcp6       0      0 :::22                   :::*                    LISTEN      1123/sshd"
        ),
        "ss -tulpn": (
            "Netid  State   Recv-Q  Send-Q   Local Address:Port    Peer Address:Port Process\n"
            "tcp    LISTEN  0       4096     0.0.0.0:22           0.0.0.0:*     users:(\"sshd\",pid=1123,fd=3)\n"
            "tcp    LISTEN  0       244      127.0.0.1:5432       0.0.0.0:*     users:(\"postgres\",pid=1345,fd=5)\n"
            "tcp    LISTEN  0       511      0.0.0.0:80           0.0.0.0:*     users:(\"nginx\",pid=1456,fd=6)"
        ),
        "cat .ssh/id_rsa": (
            "-----BEGIN OPENSSH PRIVATE KEY-----\n"
            "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\n"
            "QyNTUxOQAAACD9xP7XbB3+J6C7sLJLzK8x9y2J7h8T5sP4uP7nP9QAAAFD8rP5V/Kz+VQ\n"
            "AAAAtzc2gtZWQyNTUxOQAAACD9xP7XbB3+J6C7sLJLzK8x9y2J7h8T5sP4uP7nP9QAAAA\n"
            "FD8rP5V/Kz+VQAAAAtzc2gtZWQyNTUxOQAAACD9xP7XbB3+J6C7sLJLzK8x9y2J7h8T5sP4\n"
            "uP7nP9QAAAFD8rP5V/Kz+VQ==\n"
            "-----END OPENSSH PRIVATE KEY-----"
        ),
        "cat .ssh/authorized_keys": (
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP3E/tdsHf4noLuwskvMrzH3LYnuHxPmw/i4/uc/1 achen@dev-workstation\n"
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7vbqajDKgMBZqAbZqJVmh deploy@ci-server\n"
        ),
        "docker ps": (
            "CONTAINER ID   IMAGE              COMMAND                  CREATED       STATUS       PORTS                    NAMES\n"
            "a1b2c3d4e5f6   api-gateway:1.2    \"python app.py\"          3 hours ago   Up 3 hours   0.0.0.0:8080->8080/tcp   api-gateway-7d9f4\n"
            "b2c3d4e5f6a7   postgres:14        \"docker-entrypoint.s…\"   2 days ago    Up 2 days    0.0.0.0:5432->5432/tcp   postgres-main\n"
            "c3d4e5f6a7b8   redis:7-alpine     \"redis-server\"           2 days ago    Up 2 days    0.0.0.0:6379->6379/tcp   redis-cache"
        ),
        "history": (
            "  1  ls -la\n"
            "  2  cd projects\n"
            "  3  git clone https://git.corp.internal/api-gateway.git\n"
            "  4  cd api-gateway\n"
            "  5  python -m venv .venv\n"
            "  6  source .venv/bin/activate\n"
            "  7  pip install -r requirements.txt\n"
            "  8  python manage.py migrate\n"
            "  9  ./run_tests.sh\n"
            " 10  docker build -t api-gateway:1.2 .\n"
            " 11  docker push registry.corp.internal/api-gateway:1.2\n"
            " 12  kubectl apply -f k8s/staging/\n"
            " 13  ls -la\n"
            " 14  cat .env"
        ),
    }

    # Credential pairs that will be "accepted" — loaded at instance creation, not
    # hardcoded as static class data.  Reading from env vars allows operators to
    # rotate bait credentials across deployments without a code change.  The env
    # var ``HONEYPOT_VALID_CREDS`` is a semicolon-separated list of "user:pass"
    # pairs (e.g. ``alice:secret;bob:p@ss``).  When the env var is absent, a
    # set of well-known weak-credential pairs is generated at runtime so that
    # each honeypot instance can vary them slightly if desired.
    _VALID_CREDENTIALS: set[tuple[str, str]] = set()  # populated in __init__

    # Default weak-credential usernames used when no env var is present.
    # Passwords are intentionally trivial bait — they exist to attract
    # attackers, not to protect real systems.
    _DEFAULT_CRED_USERNAMES: tuple[str, ...] = (
        "user", "admin", "root", "ubuntu", "test",
        "deploy", "postgres", "operator",
    )

    def __init__(
        self,
        banner: str | None = None,
        version_string: str | None = None,
        config: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(banner, version_string, config)
        self._auth_stage: dict[str, str] = {}  # session_id -> auth stage
        self._failed_attempts: dict[str, int] = {}  # source_ip -> count

        # -- Bait credentials: instance-level, not static class data -----------
        # Load from HONEYPOT_VALID_CREDS env var ("user:pass;user2:pass2") or
        # generate a default set of weak bait pairs at runtime.
        env_creds = os.environ.get("HONEYPOT_VALID_CREDS", "")
        if env_creds.strip():
            self._VALID_CREDENTIALS = {
                tuple(pair.split(":", 1))  # type: ignore[misc]
                for pair in env_creds.split(";")
                if ":" in pair
            }
        else:
            # Fall back to a predictable-weak set so the honeypot still lures
            # credential-stuffing attacks.  Passwords use the username plus a
            # trivial suffix — classic weak patterns that attackers try first.
            self._VALID_CREDENTIALS = {
                (u, u) for u in self._DEFAULT_CRED_USERNAMES
            } | {
                (u, f"{u}123") for u in ("admin", "user", "test")
            } | {
                ("root", "toor"),
                ("ubuntu", "ubuntu"),
                ("deploy", "deploy2024"),
            }

        # -- Persona-aware identity (prevents cross-file hardcoded divergence) ----
        persona = self.config.get("persona", {})
        self._persona_name: str = persona.get("name", "Alex Chen")
        self._persona_username: str = persona.get("username", "achen")
        self._persona_hostname: str = persona.get("hostname", "dev-workstation")
        self._persona_domain: str = persona.get("domain", "corp.internal")
        self._persona_email: str = persona.get("email", f"{self._persona_username}@{self._persona_domain}")
        self._persona_home: str = persona.get("home_dir", "/home/user")

        # Build persona-aware shell responses so identity is consistent everywhere
        self._shell_responses = {
            **self._SHELL_RESPONSES,
            **self._build_persona_shell_responses(),
            **(self.config.get("custom_responses", {})),
        }
        self._max_auth_attempts = self.config.get("max_auth_attempts", 6)

    def _build_persona_shell_responses(self) -> dict[str, str]:
        """Generate identity-aware shell responses using the current persona.

        Prevents hardcoded identity divergence across files — every reference
        to the persona's name, username, hostname, and domain comes from the
        same config-driven values.
        """
        name = self._persona_name
        user = self._persona_username
        host = self._persona_hostname
        domain = self._persona_domain
        email = self._persona_email
        return {
            "cat /etc/passwd": (
                "root:x:0:0:root:/root:/bin/bash\n"
                "daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\n"
                "bin:x:2:2:bin:/bin:/usr/sbin/nologin\n"
                "sys:x:3:3:sys:/dev:/usr/sbin/nologin\n"
                "sync:x:4:65534:sync:/bin:/bin/sync\n"
                f"user:x:1000:1000:{name},,,:/home/user:/bin/bash\n"
                "postgres:x:106:113:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash\n"
                "www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\n"
            ),
            "cat .ssh/authorized_keys": (
                f"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP3E/tdsHf4noLuwskvMrzH3LYnuHxPmw/i4/uc/1 {user}@{host}\n"
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7vbqajDKgMBZqAbZqJVmh deploy@ci-server\n"
            ),
            "history": (
                "  1  ls -la\n"
                "  2  cd projects\n"
                f"  3  git clone https://git.{domain}/api-gateway.git\n"
                "  4  cd api-gateway\n"
                "  5  python -m venv .venv\n"
                "  6  source .venv/bin/activate\n"
                "  7  pip install -r requirements.txt\n"
                "  8  python manage.py migrate\n"
                "  9  ./run_tests.sh\n"
                " 10  docker build -t api-gateway:1.2 .\n"
                f" 11  docker push registry.{domain}/api-gateway:1.2\n"
                " 12  kubectl apply -f k8s/staging/\n"
                " 13  ls -la\n"
                " 14  cat .env"
            ),
        }

    # -- SSH Protocol Edge Case Handlers ──────────────────────────────────────

    def _handle_sftp(self) -> str:
        """Return a realistic SFTP subsystem init response."""
        return (
            "sftp> Connected to localhost.\n"
            "Changing to: /home/user\n"
            "sftp> ls\n"
            "projects    notes.txt    .ssh    .config    .cache\n"
            "sftp> pwd\n"
            "Remote working directory: /home/user\n"
            "sftp> exit\n"
            "Connection closed by escape sequence.\n"
        )

    def _handle_scp(self, command: str) -> str:
        """Return realistic SCP file transfer simulation."""
        parts = command.split()
        filename = parts[1] if len(parts) > 1 else "file.txt"
        file_size = len(filename) * 1024 + 512
        return (
            f"{filename}                                    100%  {file_size}B   "
            f"{file_size / 1024:.1f}KB/s   00:00\n"
        )

    def _handle_ssh_escape(self, command: str) -> str:
        """Handle SSH escape sequences like ~. (disconnect) and ~^Z (suspend)."""
        if command == "~.":
            return "Connection closed by escape sequence.\r\n"
        if command == "~^Z":
            return "Suspended by escape sequence. Use 'fg' to resume.\r\n"
        if command.startswith("~"):
            return f"Unknown escape sequence '{command}'. Supported: ~. ~^Z\r\n"
        return ""

    def _handle_verbose_command(self, command: str) -> str:
        """Return verbose SSH debug output when -v / -vv / -vvv flags detected."""
        verbose_level = command.count("-v")
        if "-vvv" in command:
            verbose_level = 3

        host = command.split()[-1] if command.split() else "unknown"
        output_lines = [
            f"OpenSSH_8.9p1 Ubuntu-3ubuntu0.6, OpenSSL 3.0.2 15 Mar 2022",
            f"debug1: Reading configuration data /etc/ssh/ssh_config",
            f"debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files",
            f"debug1: Connecting to {host} [10.0.2.15] port 22.",
            f"debug1: Connection established.",
            f"debug1: identity file /home/user/.ssh/id_rsa type 0",
            f"debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6",
            f"debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1",
            f"debug1: compat_banner: match: OpenSSH_8.9p1 pat OpenSSH* compat 0x04000000",
        ]
        if verbose_level >= 2:
            output_lines.extend([
                f"debug2: ssh_connect_direct: needpriv 0",
                f"debug2: kex_exchange_identification: banner line 0: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6",
                f"debug2: kex_algorithm: curve25519-sha256",
                f"debug2: host key algorithms: ssh-ed25519",
                f"debug2: ciphers ctos: chacha20-poly1305@openssh.com",
                f"debug2: MACs ctos: umac-128-etm@openssh.com",
            ])
        if verbose_level >= 3:
            output_lines.extend([
                f"debug3: send packet: type 20",
                f"debug3: receive packet: type 20",
                f"debug3: looking up kex algorithms for initiator",
                f"debug3: kex_engine_init_hdr: type 20, len 1076",
                f"debug3: kex_exchange_identification: client matches OpenSSH_8.9*",
                f"debug3: hostkeys_foreach: reading file /home/user/.ssh/known_hosts",
            ])
        output_lines.extend([
            f"debug1: Authenticating to {host}:22 as 'user'",
            f"debug1: Authentication succeeded (password).",
            f"Authenticated to {host} ([10.0.2.15]:22).",
        ])
        return "\n".join(output_lines) + "\n"

    def _handle_port_forwarding(self, command: str) -> str:
        """Handle SSH port forwarding requests (-L, -R, -D)."""
        cmd_lower = command.lower()
        if "-l" in cmd_lower or "-r" in cmd_lower or "-d" in cmd_lower:
            return (
                "bind [::1]:8080: Address already in use\n"
                "channel_setup_fwd_listener_tcpip: cannot listen to port: 8080\n"
                "Could not request local forwarding.\n"
            )
        return "Port forwarding disabled on this host.\n"

    async def start(self) -> None:
        await super().start()
        logger.info("SSH emulator listening — accepting creds after %d attempts", self._max_auth_attempts)

    async def stop(self) -> None:
        await super().stop()
        self._auth_stage.clear()
        self._failed_attempts.clear()

    async def get_banner(self) -> str:
        return self.banner

    async def handle_connection(
        self,
        context: ConnectionContext,
        raw_data: str | bytes,
    ) -> EmulatedResponse:
        """Handle SSH protocol stages: banner -> auth -> shell."""
        data = raw_data.decode() if isinstance(raw_data, bytes) else raw_data
        data = data.strip()

        # Stage detection based on session state
        stage = self._auth_stage.get(context.session_id, "banner")

        if stage == "banner":
            self._auth_stage[context.session_id] = "auth"
            return EmulatedResponse(
                payload=self.banner + "\n",
                delay_ms=50,
            )

        if stage == "auth":
            return await self._handle_auth(context, data)

        # Shell stage
        return await self._handle_shell_command(context, data)

    async def _handle_auth(
        self,
        context: ConnectionContext,
        data: str,
    ) -> EmulatedResponse:
        """Handle authentication attempts — accept after N tries for believability."""
        # Parse "user:password" or individual prompts
        if ":" in data:
            parts = data.split(":", 1)
            username, password = parts[0].strip(), parts[1].strip()
        else:
            # Treat as single-line auth attempt
            username = data.strip() or "unknown"
            password = ""

        cred_key = (username, password)
        ip_key = context.source_ip

        # Always increment failed counter per IP for realism
        self._failed_attempts[ip_key] = self._failed_attempts.get(ip_key, 0) + 1

        # Accept common weak creds immediately; accept anything after max attempts
        if cred_key in self._VALID_CREDENTIALS:
            self._auth_stage[context.session_id] = "shell"
            context.authenticated_user = username
            self._failed_attempts[ip_key] = 0
            motd = (
                "\nWelcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)\n\n"
                " * Documentation:  https://help.ubuntu.com\n"
                " * Management:     https://landscape.canonical.com\n"
                " * Support:        https://ubuntu.com/pro\n\n"
                f"  System information as of {datetime.now(timezone.utc).strftime('%c')}\n\n"
                "  System load:  0.08              Processes:             143\n"
                "  Usage of /:   24.0% of 196.00GB Users logged in:       1\n"
                "  Memory usage: 27%               IPv4 address for eth0: 10.0.2.15\n"
                "  Swap usage:   0%\n\n"
                f"Last login: {datetime.now(timezone.utc).strftime('%a %b %d %H:%M')} from {context.source_ip}\n"
            )
            return EmulatedResponse(payload=motd, delay_ms=200)

        # Failed auth
        attempts = self._failed_attempts.get(ip_key, 1)
        if attempts >= self._max_auth_attempts:
            # Eventually let them in (it's a honeypot!)
            self._auth_stage[context.session_id] = "shell"
            context.authenticated_user = username
            return EmulatedResponse(
                payload="\nAccess granted.\n$ ",
                delay_ms=300,
            )

        return EmulatedResponse(
            payload=f"Permission denied, please try again. ({attempts}/{self._max_auth_attempts})\n",
            delay_ms=500,
        )

    async def _handle_shell_command(
        self,
        context: ConnectionContext,
        command: str,
    ) -> EmulatedResponse:
        """Execute a shell command and return a realistic response."""
        self._log_command(context, command, "")

        cmd_stripped = command.strip()
        cmd_lower = cmd_stripped.lower()
        cmd_base = cmd_lower.split()[0] if cmd_lower else ""

        # SSH protocol edge cases (checked before normal shell dispatch)
        # 1. SFTP subsystem request
        if "subsystem" in cmd_lower and "sftp" in cmd_lower:
            response = self._handle_sftp()
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=100)

        # 2. SCP file transfer
        if cmd_stripped.startswith("scp "):
            response = self._handle_scp(cmd_stripped)
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=200)

        # 3. SSH escape sequences (~., ~^Z, etc.)
        if cmd_stripped.startswith("~"):
            response = self._handle_ssh_escape(cmd_stripped)
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=20)

        # 4. Verbose SSH mode (-v / -vv / -vvv)
        if "-v" in cmd_stripped and ("ssh " in cmd_lower or cmd_base == "ssh"):
            response = self._handle_verbose_command(cmd_stripped)
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=150)

        # 5. SSH port forwarding (-L, -R, -D flags)
        if cmd_base == "ssh" and any(f in cmd_stripped for f in ("-L", "-R", "-D")):
            response = self._handle_port_forwarding(cmd_stripped)
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=80)

        # Check exact match first
        if cmd_stripped in self._shell_responses:
            response = self._shell_responses[cmd_stripped]
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=30)

        # Check command base
        if cmd_base in self._shell_responses:
            response = self._shell_responses[cmd_base]
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=30)

        # Pattern-based responses
        response = self._pattern_match_response(command, context)
        if response:
            self._log_command(context, command, response)
            return EmulatedResponse(payload=response + "\n$ ", delay_ms=50)

        # Generic "command not found" with some helpful suggestions
        generic = f"{cmd_base}: command not found"
        self._log_command(context, command, generic)
        return EmulatedResponse(payload=generic + "\n$ ", delay_ms=20)

    def _pattern_match_response(self, command: str, context: ConnectionContext) -> str | None:
        """Match command patterns for dynamic responses."""
        cmd_lower = command.lower().strip()

        # File reading patterns
        if cmd_lower.startswith("cat "):
            filename = command[4:].strip()
            return self._generate_file_content(filename)

        if cmd_lower.startswith("head "):
            return f"# {command[5:].strip()}\n# Auto-generated header\nimport os\nimport sys\n\ndef main():\n    pass\n\nif __name__ == '__main__':\n    main()"

        if cmd_lower.startswith("tail "):
            return (
                "    logger.info('Processing complete')\n"
                "    return {'status': 'ok', 'processed': count}\n"
                "\n"
                "except Exception as e:\n"
                "    logger.error(f'Batch failed: {e}')\n"
                "    raise\n"
                "# EOF"
            )

        if cmd_lower.startswith("cd "):
            new_dir = command[3:].strip()
            context.working_directory = new_dir if new_dir.startswith("/") else f"{context.working_directory}/{new_dir}"
            return ""

        if cmd_lower.startswith("wget ") or cmd_lower.startswith("curl "):
            return (
                f"--{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}--  {command.split()[-1]}\n"
                f"Resolving {command.split()[-1].split('/')[2]}... 192.168.1.45\n"
                "Connecting... connected.\n"
                "HTTP request sent, awaiting response... 200 OK\n"
                "Length: 12456 (12K) [application/x-gzip]\n"
                "Saving to: 'payload.tar.gz'\n\n"
                "payload.tar.gz    100%[===================>]  12.16K  --.-KB/s    in 0.001s\n\n"
                f"'{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} (12.2 KB/s) - 'payload.tar.gz' saved [12456/12456]"
            )

        if cmd_lower.startswith("python") or cmd_lower.startswith("python3"):
            return (
                "Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux\n"
                "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n"
                ">>> "
            )

        if "sudo" in cmd_lower:
            return f"[sudo] password for {context.authenticated_user or 'user'}: "

        if cmd_lower.startswith("exit") or cmd_lower.startswith("logout"):
            self._auth_stage.pop(context.session_id, None)
            return "logout\nConnection closed."

        if "nmap" in cmd_lower:
            return (
                "Starting Nmap 7.94 ( https://nmap.org )\n"
                "Nmap scan report for localhost (127.0.0.1)\n"
                "Host is up (0.00012s latency).\n"
                "Not shown: 995 closed tcp ports (reset)\n"
                "PORT     STATE SERVICE\n"
                "22/tcp   open  ssh\n"
                "80/tcp   open  http\n"
                "443/tcp  open  https\n"
                "3306/tcp open  mysql\n"
                "5432/tcp open  postgresql\n\n"
                "Nmap done: 1 IP address (1 host up) scanned in 0.42 seconds"
            )

        return None

    def _generate_file_content(self, filename: str) -> str | None:
        """Generate realistic fake file contents."""
        fname_lower = filename.lower()

        if ".env" in fname_lower:
            domain = getattr(self, '_persona_domain', 'corp.internal')
            return (
                "# Environment configuration\n"
                f"DATABASE_URL=postgresql://postgres:pg_secret_99@db.{domain}:5432/appdb\n"
                f"REDIS_URL=redis://cache.{domain}:6379/0\n"
                "API_KEY=ak_live_51H8xYZXYzABCdefGHIjklMNOpqrSTUv\n"
                "SECRET_KEY=sk_prod_8f3a9b2c1d4e5f6a7b8c9d0e1f2a3b4c\n"
                "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\n"
                "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n"
                "STRIPE_WEBHOOK_SECRET=whsec_8f3a9b2c1d4e5f6a7b8c9d0e1f2a3b4c\n"
                "SENDGRID_API_KEY=SG.xxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n"
                "DEBUG=False\n"
                "ENVIRONMENT=staging"
            )

        if ".py" in fname_lower:
            return (
                "#!/usr/bin/env python3\n"
                "\"\"\"API Gateway service - main application module.\"\"\"\n\n"
                "import os\n"
                "import logging\n"
                "from fastapi import FastAPI, Depends, HTTPException\n"
                "from sqlalchemy import create_engine\n\n"
                "app = FastAPI(title='API Gateway', version='1.2.0')\n\n"
                "DATABASE_URL = os.getenv('DATABASE_URL', 'postgresql://localhost/appdb')\n"
                "engine = create_engine(DATABASE_URL)\n\n"
                "@app.get('/health')\n"
                "async def health_check():\n"
                "    return {'status': 'healthy', 'version': '1.2.0'}\n"
            )

        if ".sql" in fname_lower:
            return (
                "-- Database schema for payment processor\n"
                "CREATE TABLE transactions (\n"
                "    id SERIAL PRIMARY KEY,\n"
                "    user_id INTEGER NOT NULL,\n"
                "    amount DECIMAL(10,2) NOT NULL,\n"
                "    currency VARCHAR(3) DEFAULT 'USD',\n"
                "    status VARCHAR(20) DEFAULT 'pending',\n"
                "    created_at TIMESTAMP DEFAULT NOW(),\n"
                "    metadata JSONB\n"
                ");\n\n"
                "CREATE INDEX idx_transactions_user ON transactions(user_id);\n"
                "CREATE INDEX idx_transactions_created ON transactions(created_at);\n\n"
                "-- Sample data\n"
                "INSERT INTO transactions (user_id, amount, currency, status) VALUES\n"
                "(101, 299.99, 'USD', 'completed'),\n"
                "(102, 1500.00, 'EUR', 'pending'),\n"
                "(103, 49.99, 'USD', 'completed');"
            )

        if ".json" in fname_lower:
            return json.dumps(
                {
                    "service": "api-gateway",
                    "version": "1.2.0",
                    "environment": "staging",
                    "endpoints": [
                        {"path": "/api/v1/users", "method": "GET", "auth": True},
                        {"path": "/api/v1/payments", "method": "POST", "auth": True},
                        {"path": "/api/v1/health", "method": "GET", "auth": False},
                    ],
                    "database": {"host": "localhost", "port": 5432, "name": "appdb"},
                },
                indent=2,
            )

        if "password" in fname_lower or "shadow" in fname_lower:
            return (
                "root:$6$xyz$abcdef1234567890abcdef1234567890abcdef1234567890:19800:0:99999:7:::\n"
                "user:$6$abc$fedcba0987654321fedcba0987654321fedcba0987654321:19800:0:99999:7:::\n"
                "postgres:*:19800:0:99999:7:::\n"
                "www-data:*:19800:0:99999:7:::\n"
                "deploy:$6$def$1234567890abcdef1234567890abcdef1234567890abcdef:19800:0:99999:7:::\n"
            )

        if "config" in fname_lower or ".yaml" in fname_lower or ".yml" in fname_lower:
            return (
                "apiVersion: v1\n"
                "kind: ConfigMap\n"
                "metadata:\n"
                "  name: api-gateway-config\n"
                "  namespace: staging\n"
                "data:\n"
                "  DATABASE_HOST: \"postgres-main.staging.svc.cluster.local\"\n"
                "  REDIS_HOST: \"redis-cache.staging.svc.cluster.local\"\n"
                "  LOG_LEVEL: \"info\"\n"
                "  MAX_CONNECTIONS: \"1000\"\n"
                "  RATE_LIMIT_RPS: \"100\""
            )

        return f"# File: {filename}\n# Content not available or permission denied"


# ── HTTP Emulator ────────────────────────────────────────────────────────


class HTTPEmulator(ServiceEmulator):
    """Emulates an HTTP server — fake admin panel, API endpoints, and logging.

    Presents a convincing web application surface with fake admin panels,
    API endpoints, and realistic error pages.
    """

    protocol = ProtocolType.HTTP
    banner = "Server: nginx/1.24.0"
    version_string = "nginx/1.24.0"

    _ADMIN_PAGES: dict[str, str] = {
        "/admin": (
            "<!DOCTYPE html>\n"
            "<html><head><title>Admin Panel</title></head>\n"
            "<body><h1>Admin Panel v2.4</h1>\n"
            "<form method='post' action='/admin/login'>\n"
            "  <input name='username' placeholder='Username'><br>\n"
            "  <input name='password' type='password' placeholder='Password'><br>\n"
            "  <button type='submit'>Login</button></form></body></html>"
        ),
        "/admin/login": (
            "<!DOCTYPE html>\n"
            "<html><head><title>Dashboard</title></head>\n"
            "<body><h1>Dashboard</h1>\n"
            "<ul><li><a href='/admin/users'>User Management</a></li>\n"
            "<li><a href='/admin/config'>System Config</a></li>\n"
            "<li><a href='/admin/logs'>View Logs</a></li>\n"
            "<li><a href='/admin/database'>Database Admin</a></li></ul></body></html>"
        ),
        "/admin/users": (
            "<!DOCTYPE html>\n"
            "<html><head><title>Users</title></head>\n"
            "<body><h1>User Management</h1>\n"
            "<table border='1'><tr><th>ID</th><th>Username</th><th>Role</th><th>Status</th></tr>\n"
            "<tr><td>1</td><td>admin</td><td>superuser</td><td>active</td></tr>\n"
            "<tr><td>2</td><td>achen</td><td>developer</td><td>active</td></tr>\n"
            "<tr><td>3</td><td>deploy</td><td>devops</td><td>active</td></tr>\n"
            "<tr><td>4</td><td>dbadmin</td><td>db_admin</td><td>inactive</td></tr></table></body></html>"
        ),
        "/admin/config": (
            "<!DOCTYPE html>\n"
            "<html><head><title>Config</title></head>\n"
            "<body><h1>System Configuration</h1>\n"
            "<pre>{\n"
            '  "debug": false,\n'
            '  "database_url": "postgresql://postgres:***@localhost:5432/appdb",\n'
            '  "redis_url": "redis://localhost:6379/0",\n'
            '  "api_key_prefix": "ak_live_",\n'
            '  "jwt_secret": "***REDACTED***",\n'
            '  "allowed_hosts": ["*.corp.internal", "api.staging.internal"]\n'
            "}</pre></body></html>"
        ),
        "/admin/database": (
            "<!DOCTYPE html>\n"
            "<html><head><title>DB Admin</title></head>\n"
            "<body><h1>phpMyAdmin Lite</h1>\n"
            "<form method='post' action='/admin/db/query'>\n"
            "<textarea name='query' rows='5' cols='60'>SELECT * FROM users LIMIT 10;</textarea><br>\n"
            "<button type='submit'>Execute</button></form></body></html>"
        ),
        "/robots.txt": (
            "User-agent: *\n"
            "Disallow: /admin\n"
            "Disallow: /api/internal\n"
            "Disallow: /backup\n"
            "Disallow: /config\n"
            "Allow: /\n\n"
            "Sitemap: https://app.corp.internal/sitemap.xml"
        ),
        "/sitemap.xml": (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            "  <url><loc>https://app.corp.internal/</loc><priority>1.0</priority></url>\n"
            "  <url><loc>https://app.corp.internal/login</loc><priority>0.8</priority></url>\n"
            "  <url><loc>https://app.corp.internal/api/docs</loc><priority>0.6</priority></url>\n"
            "</urlset>"
        ),
    }

    _API_ENDPOINTS: dict[str, dict[str, Any]] = {
        "/api/v1/health": {
            "methods": ["GET"],
            "response": {"status": "healthy", "version": "1.2.0", "timestamp": datetime.now(timezone.utc).isoformat()},
        },
        "/api/v1/users": {
            "methods": ["GET", "POST"],
            "response": {
                "users": [
                    {"id": 1, "username": "admin", "email": "admin@corp.internal", "role": "superuser"},
                    {"id": 2, "username": "achen", "email": "achen@corp.internal", "role": "developer"},
                    {"id": 3, "username": "deploy", "email": "deploy@corp.internal", "role": "devops"},
                ],
                "total": 3,
                "page": 1,
            },
        },
        "/api/v1/auth/login": {
            "methods": ["POST"],
            "response": {
                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibmFtZSI6ImFkbWluIn0.a7XJ7y8y9z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q",
                "token_type": "bearer",
                "expires_in": 3600,
            },
        },
        "/api/v1/payments": {
            "methods": ["GET", "POST"],
            "response": {
                "transactions": [
                    {"id": "txn_101", "amount": 299.99, "currency": "USD", "status": "completed"},
                    {"id": "txn_102", "amount": 1500.00, "currency": "EUR", "status": "pending"},
                ],
            },
        },
    }

    def __init__(
        self,
        banner: str | None = None,
        version_string: str | None = None,
        config: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(banner, version_string, config)

        # -- Persona-aware identity for HTTP responses -------------------------
        persona = self.config.get("persona", {})
        self._persona_name: str = persona.get("name", "Alex Chen")
        self._persona_username: str = persona.get("username", "achen")
        self._persona_hostname: str = persona.get("hostname", "dev-workstation")
        self._persona_domain: str = persona.get("domain", "corp.internal")
        self._persona_email: str = persona.get("email", f"{self._persona_username}@{self._persona_domain}")

        self._admin_pages = {
            **self._build_persona_admin_pages(),
            **(self.config.get("custom_pages", {})),
        }
        self._api_endpoints = {
            **self._build_persona_api_endpoints(),
            **(self.config.get("custom_api", {})),
        }
        self._request_log: list[dict[str, Any]] = []

    def _build_persona_admin_pages(self) -> dict[str, str]:
        """Generate persona-aware admin page responses."""
        user = self._persona_username
        domain = self._persona_domain
        base_pages = dict(self._ADMIN_PAGES)
        # Override identity-dependent pages with persona-aware versions
        base_pages["/admin/users"] = (
            "<!DOCTYPE html>\n"
            "<html><head><title>Users</title></head>\n"
            "<body><h1>User Management</h1>\n"
            "<table border='1'><tr><th>ID</th><th>Username</th><th>Role</th><th>Status</th></tr>\n"
            "<tr><td>1</td><td>admin</td><td>superuser</td><td>active</td></tr>\n"
            f"<tr><td>2</td><td>{user}</td><td>developer</td><td>active</td></tr>\n"
            "<tr><td>3</td><td>deploy</td><td>devops</td><td>active</td></tr>\n"
            "<tr><td>4</td><td>dbadmin</td><td>db_admin</td><td>inactive</td></tr></table></body></html>"
        )
        base_pages["/admin/config"] = (
            "<!DOCTYPE html>\n"
            "<html><head><title>Config</title></head>\n"
            "<body><h1>System Configuration</h1>\n"
            "<pre>{\n"
            '  "debug": false,\n'
            '  "database_url": "postgresql://postgres:***@localhost:5432/appdb",\n'
            '  "redis_url": "redis://localhost:6379/0",\n'
            '  "api_key_prefix": "ak_live_",\n'
            '  "jwt_secret": "***REDACTED***",\n'
            f'  "allowed_hosts": ["*.{domain}", "api.staging.{domain}"]\n'
            "}</pre></body></html>"
        )
        base_pages["/robots.txt"] = (
            "User-agent: *\n"
            "Disallow: /admin\n"
            "Disallow: /api/internal\n"
            "Disallow: /backup\n"
            "Disallow: /config\n"
            "Allow: /\n\n"
            f"Sitemap: https://app.{domain}/sitemap.xml"
        )
        base_pages["/sitemap.xml"] = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"  <url><loc>https://app.{domain}/</loc><priority>1.0</priority></url>\n"
            f"  <url><loc>https://app.{domain}/login</loc><priority>0.8</priority></url>\n"
            f"  <url><loc>https://app.{domain}/api/docs</loc><priority>0.6</priority></url>\n"
            "</urlset>"
        )
        return base_pages

    def _build_persona_api_endpoints(self) -> dict[str, dict[str, Any]]:
        """Generate persona-aware API endpoint responses."""
        user = self._persona_username
        domain = self._persona_domain
        email = self._persona_email
        base_endpoints = dict(self._API_ENDPOINTS)
        base_endpoints["/api/v1/users"] = {
            "methods": ["GET", "POST"],
            "response": {
                "users": [
                    {"id": 1, "username": "admin", "email": f"admin@{domain}", "role": "superuser"},
                    {"id": 2, "username": user, "email": email, "role": "developer"},
                    {"id": 3, "username": "deploy", "email": f"deploy@{domain}", "role": "devops"},
                ],
                "total": 3,
                "page": 1,
            },
        }
        return base_endpoints

    async def start(self) -> None:
        await super().start()
        logger.info("HTTP emulator serving admin panel + API endpoints")

    async def get_banner(self) -> str:
        return self.banner

    async def handle_connection(
        self,
        context: ConnectionContext,
        raw_data: str | bytes,
    ) -> EmulatedResponse:
        """Handle HTTP requests — parse method/path and route appropriately."""
        data = raw_data.decode() if isinstance(raw_data, bytes) else raw_data

        # Parse HTTP request line
        request_line = data.split("\n")[0].strip()
        parts = request_line.split()

        if len(parts) < 2:
            return self._error_response(400, "Bad Request")

        method = parts[0].upper()
        path = parts[1] if len(parts) > 1 else "/"

        # Log the request
        self._log_http_request(context, method, path, data)

        # Route to appropriate handler
        if path in self._admin_pages:
            return EmulatedResponse(
                payload=self._admin_pages[path],
                response_type="html",
                status_code=200,
                headers=self._http_headers({"Content-Type": "text/html"}),
            )

        if path in self._api_endpoints:
            endpoint = self._api_endpoints[path]
            if method in endpoint.get("methods", ["GET"]):
                resp_body = endpoint.get("response", {})
                if isinstance(resp_body, dict):
                    # Inject timestamp
                    if "timestamp" in resp_body:
                        resp_body["timestamp"] = datetime.now(timezone.utc).isoformat()
                    resp_body = json.dumps(resp_body)
                return EmulatedResponse(
                    payload=resp_body,
                    response_type="json",
                    status_code=200,
                    headers=self._http_headers({
                        "Content-Type": "application/json",
                        "X-RateLimit-Limit": "1000",
                        "X-RateLimit-Remaining": "999",
                    }),
                )
            return self._error_response(405, "Method Not Allowed")

        # Common paths
        if path == "/" or path == "/index.html":
            return self._default_homepage()

        if path == "/login":
            return self._login_page(data)

        if path.startswith("/api/"):
            return self._error_response(404, f"API endpoint '{path}' not found")

        if path.startswith("/.env") or path.startswith("/config") or path.startswith("/backup"):
            # Tempting paths — return fake leaked data
            return self._bait_response(path)

        # Default 404
        return self._error_response(404, f"The requested URL {path} was not found on this server.")

    async def _handle_auth(
        self,
        context: ConnectionContext,
        data: str,
    ) -> EmulatedResponse:
        """HTTP has built-in auth in handle_connection via form parsing."""
        return EmulatedResponse(payload="", status_code=200)

    def _log_http_request(
        self,
        context: ConnectionContext,
        method: str,
        path: str,
        raw_data: str,
    ) -> None:
        """Log HTTP request details."""
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source_ip": context.source_ip,
            "method": method,
            "path": path,
            "raw_request": raw_data[:500],
            "session_id": context.session_id,
        }
        self._request_log.append(entry)
        self._connection_count += 1
        super()._log_command(context, f"{method} {path}", raw_data[:200])

    def _http_headers(self, extra: dict[str, str] | None = None) -> dict[str, str]:
        """Generate standard HTTP headers with Date and Server."""
        headers = {
            "Date": datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S GMT"),
            "Server": self.version_string,
        }
        if extra:
            headers.update(extra)
        return headers

    def _error_response(self, code: int, message: str) -> EmulatedResponse:
        """Generate an HTML error page."""
        html = (
            f"<!DOCTYPE html>\n"
            f"<html><head><title>{code} {message}</title></head>\n"
            f"<body><h1>{code} {message}</h1>\n"
            f"<p>The server encountered an error processing your request.</p>\n"
            f"<hr><address>{self.version_string}</address></body></html>"
        )
        return EmulatedResponse(
            payload=html,
            response_type="html",
            status_code=code,
            headers=self._http_headers({"Content-Type": "text/html"}),
        )

    def _default_homepage(self) -> EmulatedResponse:
        """Generate a default homepage."""
        html = (
            "<!DOCTYPE html>\n"
            "<html><head><title>Welcome</title></head>\n"
            "<body><h1>Welcome to Corp Services</h1>\n"
            "<p>Cloud infrastructure management platform v2.4</p>\n"
            "<ul><li><a href='/login'>Sign In</a></li>\n"
            "<li><a href='/api/v1/health'>API Health</a></li></ul></body></html>"
        )
        return EmulatedResponse(
            payload=html,
            response_type="html",
            status_code=200,
            headers=self._http_headers({"Content-Type": "text/html"}),
        )

    def _login_page(self, raw_data: str) -> EmulatedResponse:
        """Handle login page GET/POST."""
        if "POST" in raw_data[:10].upper():
            # Extract credentials from form data
            body = raw_data.split("\r\n\r\n")[-1] if "\r\n\r\n" in raw_data else ""
            credentials = {}
            for pair in body.split("&"):
                if "=" in pair:
                    k, v = pair.split("=", 1)
                    credentials[k] = v

            # Always "accept" with a redirect, then fail later
            return EmulatedResponse(
                payload=(
                    "<!DOCTYPE html>\n"
                    "<html><head><title>Processing...</title>\n"
                    "<meta http-equiv='refresh' content='2;url=/admin'></head>\n"
                    "<body><p>Authenticating...</p></body></html>"
                ),
                response_type="html",
                status_code=302,
                headers=self._http_headers({
                    "Content-Type": "text/html",
                    "Location": "/admin",
                    "Set-Cookie": "sessionid=fake_session_abc123; Path=/; HttpOnly",
                }),
            )

        return EmulatedResponse(
            payload=(
                "<!DOCTYPE html>\n"
                "<html><head><title>Login</title></head>\n"
                "<body><h1>Sign In</h1>\n"
                "<form method='post' action='/login'>\n"
                "  <input name='username' placeholder='Username'><br>\n"
                "  <input name='password' type='password' placeholder='Password'><br>\n"
                "  <button type='submit'>Login</button></form></body></html>"
            ),
            response_type="html",
            status_code=200,
            headers=self._http_headers({"Content-Type": "text/html"}),
        )

    def _bait_response(self, path: str) -> EmulatedResponse:
        """Return fake 'leaked' data for tempting paths -- persona-aware domain."""
        domain = self._persona_domain
        email = self._persona_email
        if ".env" in path:
            content = (
                f"DATABASE_URL=postgresql://postgres:pg_secret_99@db.{domain}:5432/appdb\n"
                f"REDIS_URL=redis://cache.{domain}:6379/0\n"
                f"AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\n"
                f"AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n"
                f"STRIPE_SECRET_KEY=sk_HONEYTOKEN_baitcred_notreal_xxxxxxxxxxx\n"
                f"JWT_SECRET=super_secret_jwt_key_do_not_share\n"
                f"API_KEY=ak_live_51H8xYZXYzABCdefGHIjklMNOpqrSTUv\n"
            )
        elif "backup" in path:
            content = (
                "-- MySQL dump 10.19  Distrib 10.3.38-MariaDB\n"
                "-- Host: db.corp.internal    Database: appdb\n"
                "-- ------------------------------------------------------\n"
                "DROP TABLE IF EXISTS `users`;\n"
                "CREATE TABLE `users` (\n"
                "  `id` int(11) NOT NULL AUTO_INCREMENT,\n"
                "  `username` varchar(50) NOT NULL,\n"
                "  `password_hash` varchar(255) NOT NULL,\n"
                "  `email` varchar(100) NOT NULL,\n"
                "  PRIMARY KEY (`id`)\n"
                ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"
                "INSERT INTO `users` VALUES (1,'admin','$2b$12$fakehash...','admin@corp.internal');\n"
            )
        else:
            content = "# Configuration file\n# Access restricted\n"

        return EmulatedResponse(
            payload=content,
            response_type="text",
            status_code=200,
            headers=self._http_headers({"Content-Type": "text/plain"}),
        )

    def get_request_logs(self, limit: int = 100) -> list[dict[str, Any]]:
        """Return recent HTTP request logs."""
        return self._request_log[-limit:]
